/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mastermindpap.telas;
import br.mastermindpap.medio.AtribuicaoMedio;
import javax.swing.JLabel;
import br.mastermindpap.classe.visual.Visual;
import javax.swing.JOptionPane;
/**
 *
 * @author icaro
 */
public class NivelMedio extends javax.swing.JFrame {
AtribuicaoMedio at=new AtribuicaoMedio();
Visual visual=new Visual();
    /**
     * Creates new form NivelMedio
     */
    public NivelMedio() {
        initComponents();
         JLabel[] labels={label21,label22,label23,label24};
   
   at.setLabelsresposta(labels);
   at.criarSeqAleatoria();
   
   label21.setVisible(false);
   label22.setVisible(false);
   label23.setVisible(false);
   label24.setVisible(false);
   
   btA.setVisible(true);
   btB.setVisible(false);
   btC.setVisible(false);
   btD.setVisible(false);
   btE.setVisible(false);
   btF.setVisible(false);
   btG.setVisible(false);
   btI.setVisible(false);
   btJ.setVisible(false);
   btH.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label21 = new javax.swing.JLabel();
        label22 = new javax.swing.JLabel();
        label23 = new javax.swing.JLabel();
        label24 = new javax.swing.JLabel();
        labelresI3 = new javax.swing.JLabel();
        labelI2 = new javax.swing.JLabel();
        labelI3 = new javax.swing.JLabel();
        btI = new javax.swing.JButton();
        labelresI2 = new javax.swing.JLabel();
        labelresI4 = new javax.swing.JLabel();
        labelI1 = new javax.swing.JLabel();
        labelJ4 = new javax.swing.JLabel();
        labelresJ2 = new javax.swing.JLabel();
        btA = new javax.swing.JButton();
        labelJ2 = new javax.swing.JLabel();
        labelresA1 = new javax.swing.JLabel();
        labelresA2 = new javax.swing.JLabel();
        labelresA3 = new javax.swing.JLabel();
        labelresA4 = new javax.swing.JLabel();
        labelA1 = new javax.swing.JLabel();
        labelA2 = new javax.swing.JLabel();
        labelA3 = new javax.swing.JLabel();
        labelA4 = new javax.swing.JLabel();
        btnSelcaoNiveis1 = new javax.swing.JButton();
        labelB1 = new javax.swing.JLabel();
        labelB2 = new javax.swing.JLabel();
        btB = new javax.swing.JButton();
        labelB3 = new javax.swing.JLabel();
        labelB4 = new javax.swing.JLabel();
        labelresB1 = new javax.swing.JLabel();
        labelresB2 = new javax.swing.JLabel();
        labelresB3 = new javax.swing.JLabel();
        labelresB4 = new javax.swing.JLabel();
        labelresC1 = new javax.swing.JLabel();
        labelresC2 = new javax.swing.JLabel();
        labelresC3 = new javax.swing.JLabel();
        labelresC4 = new javax.swing.JLabel();
        labelC1 = new javax.swing.JLabel();
        labelC2 = new javax.swing.JLabel();
        btC = new javax.swing.JButton();
        labelC3 = new javax.swing.JLabel();
        labelC4 = new javax.swing.JLabel();
        labelresD1 = new javax.swing.JLabel();
        labelresD3 = new javax.swing.JLabel();
        btD = new javax.swing.JButton();
        labelD1 = new javax.swing.JLabel();
        labelD3 = new javax.swing.JLabel();
        labelD4 = new javax.swing.JLabel();
        labelresD2 = new javax.swing.JLabel();
        labelD2 = new javax.swing.JLabel();
        labelresD4 = new javax.swing.JLabel();
        labelresE3 = new javax.swing.JLabel();
        labelE4 = new javax.swing.JLabel();
        btE = new javax.swing.JButton();
        labelE3 = new javax.swing.JLabel();
        labelresE1 = new javax.swing.JLabel();
        labelE2 = new javax.swing.JLabel();
        labelresE4 = new javax.swing.JLabel();
        labelE1 = new javax.swing.JLabel();
        labelresE2 = new javax.swing.JLabel();
        labelresF3 = new javax.swing.JLabel();
        labelF4 = new javax.swing.JLabel();
        btF = new javax.swing.JButton();
        labelF3 = new javax.swing.JLabel();
        labelresF1 = new javax.swing.JLabel();
        labelF2 = new javax.swing.JLabel();
        labelresF4 = new javax.swing.JLabel();
        labelresJ4 = new javax.swing.JLabel();
        labelF1 = new javax.swing.JLabel();
        btJ = new javax.swing.JButton();
        labelresF2 = new javax.swing.JLabel();
        labelresJ1 = new javax.swing.JLabel();
        labelJ1 = new javax.swing.JLabel();
        labelJ3 = new javax.swing.JLabel();
        labelresJ3 = new javax.swing.JLabel();
        labelresG3 = new javax.swing.JLabel();
        labelG4 = new javax.swing.JLabel();
        btG = new javax.swing.JButton();
        labelG3 = new javax.swing.JLabel();
        labelresG1 = new javax.swing.JLabel();
        labelG2 = new javax.swing.JLabel();
        labelresG4 = new javax.swing.JLabel();
        labelG1 = new javax.swing.JLabel();
        labelresG2 = new javax.swing.JLabel();
        btH = new javax.swing.JButton();
        labelH2 = new javax.swing.JLabel();
        labelresH1 = new javax.swing.JLabel();
        labelresH3 = new javax.swing.JLabel();
        labelresH2 = new javax.swing.JLabel();
        labelresH4 = new javax.swing.JLabel();
        labelH1 = new javax.swing.JLabel();
        labelH4 = new javax.swing.JLabel();
        labelH3 = new javax.swing.JLabel();
        btnRegras = new javax.swing.JButton();
        labelI4 = new javax.swing.JLabel();
        btnComoJogar = new javax.swing.JButton();
        labelresI1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mastermind - Nível Médio");
        setResizable(false);

        label21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        labelresI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI2MouseClicked(evt);
            }
        });

        labelI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI3MouseClicked(evt);
            }
        });

        btI.setText("comparar");
        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });

        labelresI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI1MouseClicked(evt);
            }
        });

        labelJ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ4MouseClicked(evt);
            }
        });

        labelresJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btA.setText("comparar");
        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });

        labelJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ2MouseClicked(evt);
            }
        });

        labelresA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA1MouseClicked(evt);
            }
        });

        labelA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA2MouseClicked(evt);
            }
        });

        labelA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA3MouseClicked(evt);
            }
        });

        labelA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA4MouseClicked(evt);
            }
        });

        btnSelcaoNiveis1.setText("Seleção de níveis");
        btnSelcaoNiveis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelcaoNiveis1ActionPerformed(evt);
            }
        });

        labelB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB1MouseClicked(evt);
            }
        });

        labelB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB2MouseClicked(evt);
            }
        });

        btB.setText("comparar");
        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });

        labelB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB3MouseClicked(evt);
            }
        });

        labelB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB4MouseClicked(evt);
            }
        });

        labelresB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC1MouseClicked(evt);
            }
        });

        labelC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC2MouseClicked(evt);
            }
        });

        btC.setText("comparar");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        labelC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC3MouseClicked(evt);
            }
        });

        labelC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC4MouseClicked(evt);
            }
        });

        labelresD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btD.setText("comparar");
        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });

        labelD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD1MouseClicked(evt);
            }
        });

        labelD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD3MouseClicked(evt);
            }
        });

        labelD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD4MouseClicked(evt);
            }
        });

        labelresD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD2MouseClicked(evt);
            }
        });

        labelresD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE4MouseClicked(evt);
            }
        });

        btE.setText("comparar");
        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        labelE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE3MouseClicked(evt);
            }
        });

        labelresE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE2MouseClicked(evt);
            }
        });

        labelresE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE1MouseClicked(evt);
            }
        });

        labelresE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF4MouseClicked(evt);
            }
        });

        btF.setText("comparar");
        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });

        labelF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF3MouseClicked(evt);
            }
        });

        labelresF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF2MouseClicked(evt);
            }
        });

        labelresF4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresJ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF1MouseClicked(evt);
            }
        });

        btJ.setText("comparar");
        btJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJActionPerformed(evt);
            }
        });

        labelresF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ1MouseClicked(evt);
            }
        });

        labelJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ3MouseClicked(evt);
            }
        });

        labelresJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG4MouseClicked(evt);
            }
        });

        btG.setText("comparar");
        btG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGActionPerformed(evt);
            }
        });

        labelG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG3MouseClicked(evt);
            }
        });

        labelresG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG2MouseClicked(evt);
            }
        });

        labelresG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG1MouseClicked(evt);
            }
        });

        labelresG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btH.setText("comparar");
        btH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHActionPerformed(evt);
            }
        });

        labelH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH2MouseClicked(evt);
            }
        });

        labelresH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelresH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH1MouseClicked(evt);
            }
        });

        labelH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH4MouseClicked(evt);
            }
        });

        labelH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH3MouseClicked(evt);
            }
        });

        btnRegras.setText("Regras");
        btnRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegrasActionPerformed(evt);
            }
        });

        labelI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI4MouseClicked(evt);
            }
        });

        btnComoJogar.setText("Como jogar");
        btnComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComoJogarActionPerformed(evt);
            }
        });

        labelresI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        jLabel1.setText("Cores disponíveis:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulorosa.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulovermelho.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloazul.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloverde.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulolaranja.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloamarelo.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulomarrom.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloroxo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelJ1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJ3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresJ1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresJ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresJ3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresJ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btJ))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelF3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresF3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelE3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelE4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresE3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresE4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelD4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresD4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btD))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelC3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelC4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresC3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresC4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelI1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelI2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelI3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelI4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresI1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresI2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresI3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresI4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btI))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelH3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelH4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresH3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresH4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btH))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelG3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelG4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelresG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresG3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelresG4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btG)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelcaoNiveis1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJ1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresJ1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresJ2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresJ3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresJ4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btJ, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelI1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelI2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelI3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelI4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresI1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresI2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresI3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresI4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btI, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelH1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelH2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelH3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelH4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresH1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresH2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresH3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresH4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btH, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelG1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelG2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelG3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelG4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresG1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresG2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresG3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresG4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btG, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnSelcaoNiveis1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComoJogar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelF1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelF2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelF3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelF4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresF1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresF2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresF3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresF4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btF, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelE1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelE2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelE3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelE4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresE1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresE2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresE3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresE4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btE, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelD1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelD2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelD3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelD4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresD1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresD2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresD3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresD4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btD, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelC1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelC2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelC3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelC4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresC1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresC2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresC3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelresC4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btC, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelB1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresB1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresB2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresB3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresB4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelA1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresA1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresA2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelresA4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label21)
                    .addComponent(label22)
                    .addComponent(label23)
                    .addComponent(label24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI2MouseClicked
        if (btI.isVisible()== true){
        at.definirCorLabelUsuario(labelI2);
        }
    }//GEN-LAST:event_labelI2MouseClicked

    private void labelI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI3MouseClicked
        if (btI.isVisible()== true){
        at.definirCorLabelUsuario(labelI3);
        }
    }//GEN-LAST:event_labelI3MouseClicked

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        try{
            JLabel[] labeldica={labelresI1, labelresI2, labelresI3, labelresI4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelI1,labelI2,labelI3,labelI4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btI.setVisible(false);
               btJ.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btIActionPerformed

    private void labelI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI1MouseClicked
        if (btI.isVisible()== true){
        at.definirCorLabelUsuario(labelI1);
        }
    }//GEN-LAST:event_labelI1MouseClicked

    private void labelJ4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ4MouseClicked
        if (btJ.isVisible()== true){
        at.definirCorLabelUsuario(labelJ4);
        }
    }//GEN-LAST:event_labelJ4MouseClicked

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        try{
            JLabel[] labeldica={labelresA1, labelresA2, labelresA3, labelresA4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelA1,labelA2,labelA3,labelA4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (at.isValido()== true){
               btA.setVisible(false);
               btB.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btAActionPerformed

    private void labelJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ2MouseClicked
        if (btJ.isVisible()== true){
        at.definirCorLabelUsuario(labelJ2);
        }
    }//GEN-LAST:event_labelJ2MouseClicked

    private void labelA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA1MouseClicked
        if (btA.isVisible()== true){
        at.definirCorLabelUsuario(labelA1);
        }
    }//GEN-LAST:event_labelA1MouseClicked

    private void labelA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA2MouseClicked
        if (btA.isVisible()== true){
        at.definirCorLabelUsuario(labelA2);
        }
    }//GEN-LAST:event_labelA2MouseClicked

    private void labelA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA3MouseClicked
       if (btA.isVisible()== true){
        at.definirCorLabelUsuario(labelA3);
        }
    }//GEN-LAST:event_labelA3MouseClicked

    private void labelA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA4MouseClicked
        if (btA.isVisible()== true){
        at.definirCorLabelUsuario(labelA4);
        }
    }//GEN-LAST:event_labelA4MouseClicked

    private void btnSelcaoNiveis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelcaoNiveis1ActionPerformed
        Principal principal = new Principal();

        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelcaoNiveis1ActionPerformed

    private void labelB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB1MouseClicked
        if (btB.isVisible()==true){
        at.definirCorLabelUsuario(labelB1);
        }
    }//GEN-LAST:event_labelB1MouseClicked

    private void labelB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB2MouseClicked
        if (btB.isVisible()==true){
        at.definirCorLabelUsuario(labelB2);
        }
    }//GEN-LAST:event_labelB2MouseClicked

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        try{
            JLabel[] labeldica={labelresB1, labelresB2, labelresB3, labelresB4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelB1,labelB2,labelB3,labelB4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btB.setVisible(false);
               btC.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btBActionPerformed

    private void labelB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB3MouseClicked
        if (btB.isVisible()==true){
        at.definirCorLabelUsuario(labelB3);
        }
    }//GEN-LAST:event_labelB3MouseClicked

    private void labelB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB4MouseClicked
        if (btB.isVisible()==true){
        at.definirCorLabelUsuario(labelB4);
        }
    }//GEN-LAST:event_labelB4MouseClicked

    private void labelC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC1MouseClicked
        if (btC.isVisible()==true){
        at.definirCorLabelUsuario(labelC1);
        }
    }//GEN-LAST:event_labelC1MouseClicked

    private void labelC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC2MouseClicked
        if (btC.isVisible()==true){
        at.definirCorLabelUsuario(labelC2);
        }
    }//GEN-LAST:event_labelC2MouseClicked

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        try{
            JLabel[] labeldica={labelresC1, labelresC2, labelresC3, labelresC4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelC1,labelC2,labelC3,labelC4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btC.setVisible(false);
               btD.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btCActionPerformed

    private void labelC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC3MouseClicked
        if (btC.isVisible()==true){
        at.definirCorLabelUsuario(labelC3);
        }
    }//GEN-LAST:event_labelC3MouseClicked

    private void labelC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC4MouseClicked
        if (btC.isVisible()==true){
        at.definirCorLabelUsuario(labelC4);
        }
    }//GEN-LAST:event_labelC4MouseClicked

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        try{
            JLabel[] labeldica={labelresD1, labelresD2, labelresD3, labelresD4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelD1,labelD2,labelD3,labelD4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btD.setVisible(false);
               btE.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btDActionPerformed

    private void labelD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD1MouseClicked
        if (btD.isVisible()==true){
        at.definirCorLabelUsuario(labelD1);
        }
    }//GEN-LAST:event_labelD1MouseClicked

    private void labelD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD3MouseClicked
        if (btD.isVisible()==true){
        at.definirCorLabelUsuario(labelD3);
        }
    }//GEN-LAST:event_labelD3MouseClicked

    private void labelD4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD4MouseClicked
        if (btD.isVisible()==true){
        at.definirCorLabelUsuario(labelD4);
        }
    }//GEN-LAST:event_labelD4MouseClicked

    private void labelD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD2MouseClicked
        if (btD.isVisible()==true){
        at.definirCorLabelUsuario(labelD2);
        }
    }//GEN-LAST:event_labelD2MouseClicked

    private void labelE4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE4MouseClicked
        if (btE.isVisible()==true){
        at.definirCorLabelUsuario(labelE4);
        }
    }//GEN-LAST:event_labelE4MouseClicked

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        try{
            JLabel[] labeldica={labelresE1, labelresE2, labelresE3, labelresE4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelE1,labelE2,labelE3,labelE4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btE.setVisible(false);
               btF.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btEActionPerformed

    private void labelE3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE3MouseClicked
        if (btE.isVisible()==true){
        at.definirCorLabelUsuario(labelE3);
        }
    }//GEN-LAST:event_labelE3MouseClicked

    private void labelE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE2MouseClicked
                if (btE.isVisible()==true){
        at.definirCorLabelUsuario(labelE2);
                }
    }//GEN-LAST:event_labelE2MouseClicked

    private void labelE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE1MouseClicked
        if (btE.isVisible()==true){
        at.definirCorLabelUsuario(labelE1);
        }
    }//GEN-LAST:event_labelE1MouseClicked

    private void labelF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF4MouseClicked
        if (btF.isVisible()==true){
        at.definirCorLabelUsuario(labelF4);
        }
    }//GEN-LAST:event_labelF4MouseClicked

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        try{
            JLabel[] labeldica={labelresF1, labelresF2, labelresF3, labelresF4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelF1,labelF2,labelF3,labelF4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btF.setVisible(false);
               btG.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btFActionPerformed

    private void labelF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF3MouseClicked
        if (btF.isVisible()==true){
        at.definirCorLabelUsuario(labelF3);
        }
    }//GEN-LAST:event_labelF3MouseClicked

    private void labelF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF2MouseClicked
        if (btF.isVisible()==true){
        at.definirCorLabelUsuario(labelF2);
        }
    }//GEN-LAST:event_labelF2MouseClicked

    private void labelF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF1MouseClicked
        if (btF.isVisible()==true){
        at.definirCorLabelUsuario(labelF1);
        }
    }//GEN-LAST:event_labelF1MouseClicked

    private void btJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJActionPerformed
        try{
            JLabel[] labeldica={labelresJ1, labelresJ2, labelresJ3, labelresJ4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelJ1,labelJ2,labelJ3,labelJ4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
                else{
                    Principal principal = new Principal();
                    visual.perder();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btJActionPerformed

    private void labelJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ1MouseClicked
        if (btJ.isVisible()==true){
        at.definirCorLabelUsuario(labelJ1);
        }
    }//GEN-LAST:event_labelJ1MouseClicked

    private void labelJ3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ3MouseClicked
        if (btJ.isVisible()==true){
        at.definirCorLabelUsuario(labelJ3);
        }
    }//GEN-LAST:event_labelJ3MouseClicked

    private void labelG4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG4MouseClicked
        if (btG.isVisible()==true){
        at.definirCorLabelUsuario(labelG4);
        }
    }//GEN-LAST:event_labelG4MouseClicked

    private void btGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGActionPerformed
        try{
            JLabel[] labeldica={labelresG1, labelresG2, labelresG3, labelresG4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelG1,labelG2,labelG3,labelG4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (at.isValido()== true){
               btG.setVisible(false);
               btH.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btGActionPerformed

    private void labelG3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG3MouseClicked
        if (btG.isVisible()==true){
        at.definirCorLabelUsuario(labelG3);
        }
    }//GEN-LAST:event_labelG3MouseClicked

    private void labelG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG2MouseClicked
        if (btG.isVisible()==true){
        at.definirCorLabelUsuario(labelG2);
        }
    }//GEN-LAST:event_labelG2MouseClicked

    private void labelG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG1MouseClicked
        if (btG.isVisible()==true){
        at.definirCorLabelUsuario(labelG1);
        }
    }//GEN-LAST:event_labelG1MouseClicked

    private void btHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHActionPerformed
        try{
            JLabel[] labeldica={labelresH1, labelresH2, labelresH3, labelresH4};
            at.setLabelDicas(labeldica);
            JLabel[] labelusuario={labelH1,labelH2,labelH3,labelH4};
            at.setLabelUsuario(labelusuario);

            if(at.isValido()==false){
                throw new Exception();
            }

            else{

                at.mostrarResposta();
                if(at.isVencedor()==true){
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (at.isValido()== true){
               btH.setVisible(false);
               btI.setVisible(true);
            } 
        }

        catch(Exception e){
            visual.erro();

        }
    }//GEN-LAST:event_btHActionPerformed

    private void labelH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH2MouseClicked
        if (btH.isVisible()==true){
        at.definirCorLabelUsuario(labelH2);
        }
    }//GEN-LAST:event_labelH2MouseClicked

    private void labelH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH1MouseClicked
        if (btH.isVisible()==true){
        at.definirCorLabelUsuario(labelH1);
        }
    }//GEN-LAST:event_labelH1MouseClicked

    private void labelH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH4MouseClicked
        if (btH.isVisible()==true){
        at.definirCorLabelUsuario(labelH4);
        }
    }//GEN-LAST:event_labelH4MouseClicked

    private void labelH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH3MouseClicked
        if (btH.isVisible()==true){
        at.definirCorLabelUsuario(labelH3);
        }
    }//GEN-LAST:event_labelH3MouseClicked

    private void btnRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegrasActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Acerte a sequência de cores para ganhar, so existe cores repetidas no nível Impossível.");
    }//GEN-LAST:event_btnRegrasActionPerformed

    private void labelI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI4MouseClicked
        if (btI.isVisible()==true){
        at.definirCorLabelUsuario(labelI4);
        }
    }//GEN-LAST:event_labelI4MouseClicked

    private void btnComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComoJogarActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Clique com o mouse nos botões até chegar na cor desejada, \npreencha todos os botões com cores e aperte comparar.\n \nSe voltar um bola preta você acertou a cor e o lugar certo,\nse voltar uma branca você so acertou a cor.");
    }//GEN-LAST:event_btnComoJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelMedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btE;
    private javax.swing.JButton btF;
    private javax.swing.JButton btG;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btJ;
    private javax.swing.JButton btnComoJogar;
    private javax.swing.JButton btnRegras;
    private javax.swing.JButton btnSelcaoNiveis1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel label21;
    public static javax.swing.JLabel label22;
    public static javax.swing.JLabel label23;
    public static javax.swing.JLabel label24;
    private javax.swing.JLabel labelA1;
    private javax.swing.JLabel labelA2;
    private javax.swing.JLabel labelA3;
    private javax.swing.JLabel labelA4;
    private javax.swing.JLabel labelB1;
    private javax.swing.JLabel labelB2;
    private javax.swing.JLabel labelB3;
    private javax.swing.JLabel labelB4;
    private javax.swing.JLabel labelC1;
    private javax.swing.JLabel labelC2;
    private javax.swing.JLabel labelC3;
    private javax.swing.JLabel labelC4;
    private javax.swing.JLabel labelD1;
    private javax.swing.JLabel labelD2;
    private javax.swing.JLabel labelD3;
    private javax.swing.JLabel labelD4;
    private javax.swing.JLabel labelE1;
    private javax.swing.JLabel labelE2;
    private javax.swing.JLabel labelE3;
    private javax.swing.JLabel labelE4;
    private javax.swing.JLabel labelF1;
    private javax.swing.JLabel labelF2;
    private javax.swing.JLabel labelF3;
    private javax.swing.JLabel labelF4;
    private javax.swing.JLabel labelG1;
    private javax.swing.JLabel labelG2;
    private javax.swing.JLabel labelG3;
    private javax.swing.JLabel labelG4;
    private javax.swing.JLabel labelH1;
    private javax.swing.JLabel labelH2;
    private javax.swing.JLabel labelH3;
    private javax.swing.JLabel labelH4;
    private javax.swing.JLabel labelI1;
    private javax.swing.JLabel labelI2;
    private javax.swing.JLabel labelI3;
    private javax.swing.JLabel labelI4;
    private javax.swing.JLabel labelJ1;
    private javax.swing.JLabel labelJ2;
    private javax.swing.JLabel labelJ3;
    private javax.swing.JLabel labelJ4;
    private javax.swing.JLabel labelresA1;
    private javax.swing.JLabel labelresA2;
    private javax.swing.JLabel labelresA3;
    private javax.swing.JLabel labelresA4;
    private javax.swing.JLabel labelresB1;
    private javax.swing.JLabel labelresB2;
    private javax.swing.JLabel labelresB3;
    private javax.swing.JLabel labelresB4;
    private javax.swing.JLabel labelresC1;
    private javax.swing.JLabel labelresC2;
    private javax.swing.JLabel labelresC3;
    private javax.swing.JLabel labelresC4;
    private javax.swing.JLabel labelresD1;
    private javax.swing.JLabel labelresD2;
    private javax.swing.JLabel labelresD3;
    private javax.swing.JLabel labelresD4;
    private javax.swing.JLabel labelresE1;
    private javax.swing.JLabel labelresE2;
    private javax.swing.JLabel labelresE3;
    private javax.swing.JLabel labelresE4;
    private javax.swing.JLabel labelresF1;
    private javax.swing.JLabel labelresF2;
    private javax.swing.JLabel labelresF3;
    private javax.swing.JLabel labelresF4;
    private javax.swing.JLabel labelresG1;
    private javax.swing.JLabel labelresG2;
    private javax.swing.JLabel labelresG3;
    private javax.swing.JLabel labelresG4;
    private javax.swing.JLabel labelresH1;
    private javax.swing.JLabel labelresH2;
    private javax.swing.JLabel labelresH3;
    private javax.swing.JLabel labelresH4;
    private javax.swing.JLabel labelresI1;
    private javax.swing.JLabel labelresI2;
    private javax.swing.JLabel labelresI3;
    private javax.swing.JLabel labelresI4;
    private javax.swing.JLabel labelresJ1;
    private javax.swing.JLabel labelresJ2;
    private javax.swing.JLabel labelresJ3;
    private javax.swing.JLabel labelresJ4;
    // End of variables declaration//GEN-END:variables
}
