/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mastermindpap.telas;

import br.mastermindpap.facil.AtribuicaoFacil;
import br.mastermindpap.classe.visual.Visual;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author icaro
 */
public class NivelFacil extends javax.swing.JFrame {

    AtribuicaoFacil a;
    ;
   Visual visual;

    /**
     * Creates new form SelecaoNivel
     */
    public NivelFacil() {
        this.visual = new Visual();
        this.a = new AtribuicaoFacil();

        initComponents();

        JLabel[] labelresposta = {label2, label3, label4, label5};
        a.setLabelsresposta(labelresposta);
        a.criarSeqAleatoria();

        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);

        btA.setVisible(true);
        btB.setVisible(false);
        btC.setVisible(false);
        btD.setVisible(false);
        btE.setVisible(false);
        btF.setVisible(false);
        btG.setVisible(false);
        btH.setVisible(false);
        btI.setVisible(false);
        btJ.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btA = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        labelAres1 = new javax.swing.JLabel();
        labelAres2 = new javax.swing.JLabel();
        labelAres3 = new javax.swing.JLabel();
        labelAres4 = new javax.swing.JLabel();
        labelA1 = new javax.swing.JLabel();
        labelA2 = new javax.swing.JLabel();
        labelA3 = new javax.swing.JLabel();
        labelA4 = new javax.swing.JLabel();
        btnSelcaoNiveis = new javax.swing.JButton();
        labelB1 = new javax.swing.JLabel();
        labelB2 = new javax.swing.JLabel();
        btB = new javax.swing.JButton();
        labelB3 = new javax.swing.JLabel();
        labelB4 = new javax.swing.JLabel();
        labelBres1 = new javax.swing.JLabel();
        labelBres2 = new javax.swing.JLabel();
        labelBres3 = new javax.swing.JLabel();
        labelBres4 = new javax.swing.JLabel();
        labelCres1 = new javax.swing.JLabel();
        labelCres2 = new javax.swing.JLabel();
        labelCres3 = new javax.swing.JLabel();
        labelCres4 = new javax.swing.JLabel();
        labelC1 = new javax.swing.JLabel();
        labelC2 = new javax.swing.JLabel();
        btC = new javax.swing.JButton();
        labelC3 = new javax.swing.JLabel();
        labelC4 = new javax.swing.JLabel();
        labelDres1 = new javax.swing.JLabel();
        labelDres3 = new javax.swing.JLabel();
        btD = new javax.swing.JButton();
        labelD1 = new javax.swing.JLabel();
        labelD3 = new javax.swing.JLabel();
        labelD4 = new javax.swing.JLabel();
        labelDres2 = new javax.swing.JLabel();
        labelD2 = new javax.swing.JLabel();
        labelDres4 = new javax.swing.JLabel();
        labelEres3 = new javax.swing.JLabel();
        labelE4 = new javax.swing.JLabel();
        btE = new javax.swing.JButton();
        labelE3 = new javax.swing.JLabel();
        labelEres1 = new javax.swing.JLabel();
        labelE2 = new javax.swing.JLabel();
        labelEres4 = new javax.swing.JLabel();
        labelE1 = new javax.swing.JLabel();
        labelEres2 = new javax.swing.JLabel();
        labelFres3 = new javax.swing.JLabel();
        labelF4 = new javax.swing.JLabel();
        btF = new javax.swing.JButton();
        labelF3 = new javax.swing.JLabel();
        labelFres1 = new javax.swing.JLabel();
        labelF2 = new javax.swing.JLabel();
        labelFres4 = new javax.swing.JLabel();
        labelF1 = new javax.swing.JLabel();
        labelFres2 = new javax.swing.JLabel();
        labelGres3 = new javax.swing.JLabel();
        labelG4 = new javax.swing.JLabel();
        btG = new javax.swing.JButton();
        labelG3 = new javax.swing.JLabel();
        labelGres1 = new javax.swing.JLabel();
        labelG2 = new javax.swing.JLabel();
        labelGres4 = new javax.swing.JLabel();
        labelG1 = new javax.swing.JLabel();
        labelGres2 = new javax.swing.JLabel();
        btH = new javax.swing.JButton();
        labelH2 = new javax.swing.JLabel();
        labelHres1 = new javax.swing.JLabel();
        labelHres3 = new javax.swing.JLabel();
        labelHres2 = new javax.swing.JLabel();
        labelHres4 = new javax.swing.JLabel();
        labelH1 = new javax.swing.JLabel();
        labelH4 = new javax.swing.JLabel();
        labelH3 = new javax.swing.JLabel();
        labelI4 = new javax.swing.JLabel();
        labelIres1 = new javax.swing.JLabel();
        labelIres3 = new javax.swing.JLabel();
        labelI2 = new javax.swing.JLabel();
        labelI3 = new javax.swing.JLabel();
        btI = new javax.swing.JButton();
        labelIres2 = new javax.swing.JLabel();
        labelIres4 = new javax.swing.JLabel();
        labelI1 = new javax.swing.JLabel();
        labelJ4 = new javax.swing.JLabel();
        labelJres2 = new javax.swing.JLabel();
        labelJ2 = new javax.swing.JLabel();
        labelJres4 = new javax.swing.JLabel();
        btJ = new javax.swing.JButton();
        labelJres1 = new javax.swing.JLabel();
        labelJ1 = new javax.swing.JLabel();
        labelJ3 = new javax.swing.JLabel();
        labelJres3 = new javax.swing.JLabel();
        btnRegras = new javax.swing.JButton();
        btnComoJogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mastermind - Nível Fácil");
        setResizable(false);

        btA.setText("comparar");
        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N

        labelAres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelAres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelAres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelAres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA1MouseClicked(evt);
            }
        });

        labelA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA2MouseClicked(evt);
            }
        });

        labelA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA3MouseClicked(evt);
            }
        });

        labelA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelA4MouseClicked(evt);
            }
        });

        btnSelcaoNiveis.setText("Seleção de níveis");
        btnSelcaoNiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelcaoNiveisActionPerformed(evt);
            }
        });

        labelB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB1MouseClicked(evt);
            }
        });

        labelB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB2MouseClicked(evt);
            }
        });

        btB.setText("comparar");
        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });

        labelB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB3MouseClicked(evt);
            }
        });

        labelB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelB4MouseClicked(evt);
            }
        });

        labelBres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelBres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelBres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelBres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelCres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelCres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelCres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelCres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC1MouseClicked(evt);
            }
        });

        labelC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC2MouseClicked(evt);
            }
        });

        btC.setText("comparar");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        labelC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC3MouseClicked(evt);
            }
        });

        labelC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelC4MouseClicked(evt);
            }
        });

        labelDres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelDres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btD.setText("comparar");
        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });

        labelD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD1MouseClicked(evt);
            }
        });

        labelD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD3MouseClicked(evt);
            }
        });

        labelD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD4MouseClicked(evt);
            }
        });

        labelDres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelD2MouseClicked(evt);
            }
        });

        labelDres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelEres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE4MouseClicked(evt);
            }
        });

        btE.setText("comparar");
        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        labelE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE3MouseClicked(evt);
            }
        });

        labelEres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE2MouseClicked(evt);
            }
        });

        labelEres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelE1MouseClicked(evt);
            }
        });

        labelEres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelFres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF4MouseClicked(evt);
            }
        });

        btF.setText("comparar");
        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });

        labelF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF3MouseClicked(evt);
            }
        });

        labelFres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF2MouseClicked(evt);
            }
        });

        labelFres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelF1MouseClicked(evt);
            }
        });

        labelFres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelGres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG4MouseClicked(evt);
            }
        });

        btG.setText("comparar");
        btG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGActionPerformed(evt);
            }
        });

        labelG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG3MouseClicked(evt);
            }
        });

        labelGres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG2MouseClicked(evt);
            }
        });

        labelGres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelG1MouseClicked(evt);
            }
        });

        labelGres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btH.setText("comparar");
        btH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHActionPerformed(evt);
            }
        });

        labelH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH2MouseClicked(evt);
            }
        });

        labelHres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelHres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelHres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelHres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH1MouseClicked(evt);
            }
        });

        labelH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH4MouseClicked(evt);
            }
        });

        labelH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelH3MouseClicked(evt);
            }
        });

        labelI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI4MouseClicked(evt);
            }
        });

        labelIres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelIres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI2MouseClicked(evt);
            }
        });

        labelI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI3MouseClicked(evt);
            }
        });

        btI.setText("comparar");
        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });

        labelIres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelIres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelI1MouseClicked(evt);
            }
        });

        labelJ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ4MouseClicked(evt);
            }
        });

        labelJres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ2MouseClicked(evt);
            }
        });

        labelJres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btJ.setText("comparar");
        btJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJActionPerformed(evt);
            }
        });

        labelJres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        labelJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ1MouseClicked(evt);
            }
        });

        labelJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobranco.png"))); // NOI18N
        labelJ3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJ3MouseClicked(evt);
            }
        });

        labelJres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulobrancopeq.png"))); // NOI18N

        btnRegras.setText("Regras");
        btnRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegrasActionPerformed(evt);
            }
        });

        btnComoJogar.setText("Como jogar");
        btnComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComoJogarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cores disponíveis:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulorosa.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulovermelho.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloazul.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloverde.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circulolaranja.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/mastermindpap/imagens/circuloamarelo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelC2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelC3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelC4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelJ1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJ2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJ3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJ4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelJres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btJ))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelBres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btB))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelA2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelA3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelA4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelAres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btA))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2)
                                .addGap(3, 3, 3)
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelI1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelI2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelI3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelI4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelIres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelH1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelH2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelH3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelH4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelHres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelHres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelHres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelHres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btH))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelG1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelG2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelG3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelG4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelGres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btG))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelF2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelF3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelF4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelE1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelE2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelE3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelE4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelD2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelD3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelD4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelDres1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDres2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDres3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDres4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btD)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSelcaoNiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJ1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJ4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJres1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJres2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJres3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJres4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btJ, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelI1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelI2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelI3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelI4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btI, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelH1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelH2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelH3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelH4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btH, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelG1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelG2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelG3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelG4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelGres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelGres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelGres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelGres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btG, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelF1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelF2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelF3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelF4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelE1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelE2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelE3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelE4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btE, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelD1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelD2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelD3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelD4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDres1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDres2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDres3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDres4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btD, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSelcaoNiveis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComoJogar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelC1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelC2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelC3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelC4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCres1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCres2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCres3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCres4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelB1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelB4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBres1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBres2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBres3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBres4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelA1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelA4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAres1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAres2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAres3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAres4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4)
                    .addComponent(label5))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        try {
            JLabel[] labeldica = {labelAres1, labelAres2, labelAres3, labelAres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelA1, labelA2, labelA3, labelA4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (a.isValido() == true) {
                btA.setVisible(false);
                btB.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btAActionPerformed

    private void labelA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA1MouseClicked
        if (btA.isVisible() == true) {
            a.definirCorLabelUsuario(labelA1);
        }
    }//GEN-LAST:event_labelA1MouseClicked

    private void labelA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA4MouseClicked
        if (btA.isVisible() == true) {
            a.definirCorLabelUsuario(labelA4);
        }
    }//GEN-LAST:event_labelA4MouseClicked

    private void labelA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA2MouseClicked
        if (btA.isVisible() == true) {
            a.definirCorLabelUsuario(labelA2);
        }
    }//GEN-LAST:event_labelA2MouseClicked

    private void labelA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA3MouseClicked
        if (btA.isVisible() == true) {
            a.definirCorLabelUsuario(labelA3);
        }
    }//GEN-LAST:event_labelA3MouseClicked

    private void btnSelcaoNiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelcaoNiveisActionPerformed
        Principal principal = new Principal();

        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelcaoNiveisActionPerformed

    private void labelB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB1MouseClicked
        if (btB.isVisible() == true) {
            a.definirCorLabelUsuario(labelB1);
        }
    }//GEN-LAST:event_labelB1MouseClicked

    private void labelB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB2MouseClicked
        if (btB.isVisible() == true) {
            a.definirCorLabelUsuario(labelB2);
        }
    }//GEN-LAST:event_labelB2MouseClicked

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        try {
            JLabel[] labeldica = {labelBres1, labelBres2, labelBres3, labelBres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelB1, labelB2, labelB3, labelB4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (a.isValido() == true) {
                btB.setVisible(false);
                btC.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btBActionPerformed

    private void labelB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB3MouseClicked
        if (btB.isVisible() == true) {
            a.definirCorLabelUsuario(labelB3);
        }
    }//GEN-LAST:event_labelB3MouseClicked

    private void labelB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelB4MouseClicked
        if (btB.isVisible() == true) {
            a.definirCorLabelUsuario(labelB4);
        }
    }//GEN-LAST:event_labelB4MouseClicked

    private void labelC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC1MouseClicked
        if (btC.isVisible() == true) {
            a.definirCorLabelUsuario(labelC1);
        }
    }//GEN-LAST:event_labelC1MouseClicked

    private void labelC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC2MouseClicked
        if (btC.isVisible() == true) {
            a.definirCorLabelUsuario(labelC2);
        }
    }//GEN-LAST:event_labelC2MouseClicked

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        try {
            JLabel[] labeldica = {labelCres1, labelCres2, labelCres3, labelCres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelC1, labelC2, labelC3, labelC4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (a.isValido() == true) {
                btC.setVisible(false);
                btD.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btCActionPerformed

    private void labelC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC3MouseClicked
        if (btC.isVisible() == true) {
            a.definirCorLabelUsuario(labelC3);
        }
    }//GEN-LAST:event_labelC3MouseClicked

    private void labelC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelC4MouseClicked
        if (btC.isVisible() == true) {
            a.definirCorLabelUsuario(labelC4);
        }
    }//GEN-LAST:event_labelC4MouseClicked

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        try {
            JLabel[] labeldica = {labelDres1, labelDres2, labelDres3, labelDres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelD1, labelD2, labelD3, labelD4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (a.isValido() == true) {
                btD.setVisible(false);
                btE.setVisible(true);
            }

        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btDActionPerformed

    private void labelD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD1MouseClicked
        if (btD.isVisible() == true) {
            a.definirCorLabelUsuario(labelD1);
        }
    }//GEN-LAST:event_labelD1MouseClicked

    private void labelD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD3MouseClicked
        if (btD.isVisible() == true) {
            a.definirCorLabelUsuario(labelD3);
        }
    }//GEN-LAST:event_labelD3MouseClicked

    private void labelD4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD4MouseClicked
        if (btD.isVisible() == true) {
            a.definirCorLabelUsuario(labelD4);
        }
    }//GEN-LAST:event_labelD4MouseClicked

    private void labelD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelD2MouseClicked
        if (btD.isVisible() == true) {
            a.definirCorLabelUsuario(labelD2);
        }
    }//GEN-LAST:event_labelD2MouseClicked

    private void labelE4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE4MouseClicked
        if (btE.isVisible() == true) {
            a.definirCorLabelUsuario(labelE4);
        }
    }//GEN-LAST:event_labelE4MouseClicked

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        try {
            JLabel[] labeldica = {labelEres1, labelEres2, labelEres3, labelEres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelE1, labelE2, labelE3, labelE4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (a.isValido() == true) {
                btE.setVisible(false);
                btF.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btEActionPerformed

    private void labelE3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE3MouseClicked
        if (btE.isVisible() == true) {
            a.definirCorLabelUsuario(labelE3);
        }
    }//GEN-LAST:event_labelE3MouseClicked

    private void labelE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE2MouseClicked
        if (btE.isVisible() == true) {
            a.definirCorLabelUsuario(labelE2);
        }
    }//GEN-LAST:event_labelE2MouseClicked

    private void labelE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelE1MouseClicked
        if (btE.isVisible() == true) {
            a.definirCorLabelUsuario(labelE1);
        }
    }//GEN-LAST:event_labelE1MouseClicked

    private void labelF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF4MouseClicked
        if (btF.isVisible() == true) {
            a.definirCorLabelUsuario(labelF4);
        }
    }//GEN-LAST:event_labelF4MouseClicked

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        try {
            JLabel[] labeldica = {labelFres1, labelFres2, labelFres3, labelFres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelF1, labelF2, labelF3, labelF4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (a.isValido() == true) {
                btF.setVisible(false);
                btG.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btFActionPerformed

    private void labelF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF3MouseClicked
        if (btF.isVisible() == true) {
            a.definirCorLabelUsuario(labelF3);
        }
    }//GEN-LAST:event_labelF3MouseClicked

    private void labelF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF2MouseClicked
        if (btF.isVisible() == true) {
            a.definirCorLabelUsuario(labelF2);
        }
    }//GEN-LAST:event_labelF2MouseClicked

    private void labelF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelF1MouseClicked
        if (btF.isVisible() == true) {
            a.definirCorLabelUsuario(labelF1);
        }
    }//GEN-LAST:event_labelF1MouseClicked

    private void labelG4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG4MouseClicked
        if (btG.isVisible() == true) {
            a.definirCorLabelUsuario(labelG4);
        }
    }//GEN-LAST:event_labelG4MouseClicked

    private void btGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGActionPerformed
        try {
            JLabel[] labeldica = {labelGres1, labelGres2, labelGres3, labelGres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelG1, labelG2, labelG3, labelG4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);

                }
            }
            if (a.isValido() == true) {
                btG.setVisible(false);
                btH.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btGActionPerformed

    private void labelG3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG3MouseClicked
        if (btG.isVisible() == true) {
            a.definirCorLabelUsuario(labelG3);
        }
    }//GEN-LAST:event_labelG3MouseClicked

    private void labelG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG2MouseClicked
        if (btG.isVisible() == true) {
            a.definirCorLabelUsuario(labelG2);
        }
    }//GEN-LAST:event_labelG2MouseClicked

    private void labelG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelG1MouseClicked
        if (btG.isVisible() == true) {
            a.definirCorLabelUsuario(labelG1);
        }
    }//GEN-LAST:event_labelG1MouseClicked

    private void btHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHActionPerformed
        try {
            JLabel[] labeldica = {labelHres1, labelHres2, labelHres3, labelHres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelH1, labelH2, labelH3, labelH4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
            if (a.isValido() == true) {
                btH.setVisible(false);
                btI.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btHActionPerformed

    private void labelH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH2MouseClicked
        if (btH.isVisible() == true) {
            a.definirCorLabelUsuario(labelH2);
        }
    }//GEN-LAST:event_labelH2MouseClicked

    private void labelH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH1MouseClicked
        if (btH.isVisible() == true) {
            a.definirCorLabelUsuario(labelH1);
        }
    }//GEN-LAST:event_labelH1MouseClicked

    private void labelH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH4MouseClicked
        if (btH.isVisible() == true) {
            a.definirCorLabelUsuario(labelH4);
        }
    }//GEN-LAST:event_labelH4MouseClicked

    private void labelH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelH3MouseClicked
        if (btH.isVisible() == true) {
            a.definirCorLabelUsuario(labelH3);
        }
    }//GEN-LAST:event_labelH3MouseClicked

    private void labelI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI4MouseClicked
        if (btI.isVisible() == true) {
            a.definirCorLabelUsuario(labelI4);
        }
    }//GEN-LAST:event_labelI4MouseClicked

    private void labelI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI2MouseClicked
        if (btI.isVisible() == true) {
            a.definirCorLabelUsuario(labelI2);
        }
    }//GEN-LAST:event_labelI2MouseClicked

    private void labelI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI3MouseClicked
        if (btI.isVisible() == true) {
            a.definirCorLabelUsuario(labelI3);
        }
    }//GEN-LAST:event_labelI3MouseClicked

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        try {
            JLabel[] labeldica = {labelIres1, labelIres2, labelIres3, labelIres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelI1, labelI2, labelI3, labelI4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                }

            }
            if (a.isValido() == true) {
                btI.setVisible(false);
                btJ.setVisible(true);
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btIActionPerformed

    private void labelI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI1MouseClicked
        if (btI.isVisible() == true) {
            a.definirCorLabelUsuario(labelI1);
        }
    }//GEN-LAST:event_labelI1MouseClicked

    private void labelJ4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ4MouseClicked
        if (btJ.isVisible() == true) {
            a.definirCorLabelUsuario(labelJ4);
        }
    }//GEN-LAST:event_labelJ4MouseClicked

    private void labelJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ2MouseClicked
        if (btJ.isVisible() == true) {
            a.definirCorLabelUsuario(labelJ2);
        }
    }//GEN-LAST:event_labelJ2MouseClicked

    private void btJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJActionPerformed
        try {
            JLabel[] labeldica = {labelJres1, labelJres2, labelJres3, labelJres4};
            a.setLabelDicas(labeldica);
            JLabel[] labelusuario = {labelJ1, labelJ2, labelJ3, labelJ4};
            a.setLabelUsuario(labelusuario);

            if (a.isValido() == false) {
                throw new Exception();
            } else {

                a.mostrarResposta();
                if (a.isVencedor() == true) {
                    Principal principal = new Principal();
                    visual.vencer();
                    this.dispose();
                    principal.setVisible(true);
                } else {
                    Principal principal = new Principal();
                    visual.perder();
                    this.dispose();
                    principal.setVisible(true);
                }
            }
        } catch (Exception e) {
            visual.erro();

        }
    }//GEN-LAST:event_btJActionPerformed

    private void labelJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ1MouseClicked
        if (btJ.isVisible() == true) {
            a.definirCorLabelUsuario(labelJ1);
        }
    }//GEN-LAST:event_labelJ1MouseClicked

    private void labelJ3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJ3MouseClicked
        if (btJ.isVisible() == true) {
            a.definirCorLabelUsuario(labelJ3);
        }
    }//GEN-LAST:event_labelJ3MouseClicked

    private void btnRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegrasActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Acerte a sequência de cores para ganhar, so existe cores repetidas no nível Impossível.");
    }//GEN-LAST:event_btnRegrasActionPerformed

    private void btnComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComoJogarActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Clique com o mouse nos botões até chegar na cor desejada, \npreencha todos os botões com cores e aperte comparar.\n \nSe voltar um bola preta você acertou a cor e o lugar certo,\nse voltar uma branca você so acertou a cor.");
    }//GEN-LAST:event_btnComoJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btE;
    private javax.swing.JButton btF;
    private javax.swing.JButton btG;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btJ;
    private javax.swing.JButton btnComoJogar;
    private javax.swing.JButton btnRegras;
    private javax.swing.JButton btnSelcaoNiveis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelA1;
    private javax.swing.JLabel labelA2;
    private javax.swing.JLabel labelA3;
    private javax.swing.JLabel labelA4;
    private javax.swing.JLabel labelAres1;
    private javax.swing.JLabel labelAres2;
    private javax.swing.JLabel labelAres3;
    private javax.swing.JLabel labelAres4;
    private javax.swing.JLabel labelB1;
    private javax.swing.JLabel labelB2;
    private javax.swing.JLabel labelB3;
    private javax.swing.JLabel labelB4;
    private javax.swing.JLabel labelBres1;
    private javax.swing.JLabel labelBres2;
    private javax.swing.JLabel labelBres3;
    private javax.swing.JLabel labelBres4;
    private javax.swing.JLabel labelC1;
    private javax.swing.JLabel labelC2;
    private javax.swing.JLabel labelC3;
    private javax.swing.JLabel labelC4;
    private javax.swing.JLabel labelCres1;
    private javax.swing.JLabel labelCres2;
    private javax.swing.JLabel labelCres3;
    private javax.swing.JLabel labelCres4;
    private javax.swing.JLabel labelD1;
    private javax.swing.JLabel labelD2;
    private javax.swing.JLabel labelD3;
    private javax.swing.JLabel labelD4;
    private javax.swing.JLabel labelDres1;
    private javax.swing.JLabel labelDres2;
    private javax.swing.JLabel labelDres3;
    private javax.swing.JLabel labelDres4;
    private javax.swing.JLabel labelE1;
    private javax.swing.JLabel labelE2;
    private javax.swing.JLabel labelE3;
    private javax.swing.JLabel labelE4;
    private javax.swing.JLabel labelEres1;
    private javax.swing.JLabel labelEres2;
    private javax.swing.JLabel labelEres3;
    private javax.swing.JLabel labelEres4;
    private javax.swing.JLabel labelF1;
    private javax.swing.JLabel labelF2;
    private javax.swing.JLabel labelF3;
    private javax.swing.JLabel labelF4;
    private javax.swing.JLabel labelFres1;
    private javax.swing.JLabel labelFres2;
    private javax.swing.JLabel labelFres3;
    private javax.swing.JLabel labelFres4;
    private javax.swing.JLabel labelG1;
    private javax.swing.JLabel labelG2;
    private javax.swing.JLabel labelG3;
    private javax.swing.JLabel labelG4;
    private javax.swing.JLabel labelGres1;
    private javax.swing.JLabel labelGres2;
    private javax.swing.JLabel labelGres3;
    private javax.swing.JLabel labelGres4;
    private javax.swing.JLabel labelH1;
    private javax.swing.JLabel labelH2;
    private javax.swing.JLabel labelH3;
    private javax.swing.JLabel labelH4;
    private javax.swing.JLabel labelHres1;
    private javax.swing.JLabel labelHres2;
    private javax.swing.JLabel labelHres3;
    private javax.swing.JLabel labelHres4;
    private javax.swing.JLabel labelI1;
    private javax.swing.JLabel labelI2;
    private javax.swing.JLabel labelI3;
    private javax.swing.JLabel labelI4;
    private javax.swing.JLabel labelIres1;
    private javax.swing.JLabel labelIres2;
    private javax.swing.JLabel labelIres3;
    private javax.swing.JLabel labelIres4;
    private javax.swing.JLabel labelJ1;
    private javax.swing.JLabel labelJ2;
    private javax.swing.JLabel labelJ3;
    private javax.swing.JLabel labelJ4;
    private javax.swing.JLabel labelJres1;
    private javax.swing.JLabel labelJres2;
    private javax.swing.JLabel labelJres3;
    private javax.swing.JLabel labelJres4;
    // End of variables declaration//GEN-END:variables
}
